name: Build macOS

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install pygame pyinstaller

      - name: Build ChaosBall
        working-directory: gameVersion8
        run: |
          pyinstaller ChaosBall.spec

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ChaosBall-macOS
          path: gameVersion8/dist